### ISSUE TITLE
 Datastore fetch options :prefetch-size and :chunk-size give an exception

### ISSUE THREAD

**Issue by jorisbontje** [gcv/appengine-magic#12]
The Datastore fetch options `:prefetch-size` and `:chunk-size` give the following error:

```
java.lang.IllegalArgumentException: No matching field found: prefetchSize for class java.lang.Integer
at clojure.lang.Reflector.getInstanceField(Reflector.java:245)
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:267)
at appengine_magic.services.datastore$make_fetch_options_object.invoke(datastore.clj:294)
at appengine_magic.services.datastore$query_helper.invoke(datastore.clj:453)
```

This seems to be caused by a missing `fetch-options-object` argument in the setter calls, which causes the `.prefetchSize` and `.chunkSize` to be executed on the Integer argument itself instead of on the `FetchOptions` object. This happens with v0.4.0 but also applies to the master / v0.3.3 branch.

**Comment by gcv** [comment]
I fixed the problem in master and released v0.3.4. Also fixed in the latest v0.4.0 and 0.4.0-SNAPSHOT in Clojars.

Thank you for the bug report.
