### ISSUE TITLE
Can't resolve appengine-magic

### ISSUE THREAD

**Issue by mvid** [gcv/appengine-magic#33]
$ lein deps
Copying 19 files to /home/mvid/development/clojure/checkin/lib
Copying 21 files to /home/mvid/development/clojure/checkin/lib/dev
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file (NO_SOURCE_FILE:0)
        at clojure.lang.Compiler.eval(Compiler.java:5440)
        at clojure.lang.Compiler.eval(Compiler.java:5391)
        at clojure.core$eval.invoke(core.clj:2382)
        at clojure.main$eval_opt.invoke(main.clj:235)
        at clojure.main$initialize.invoke(main.clj:254)
        at clojure.main$script_opt.invoke(main.clj:270)
        at clojure.main$main.doInvoke(main.clj:354)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at clojure.lang.Var.invoke(Var.java:377)
        at clojure.lang.AFn.applyToHelper(AFn.java:172)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
        at clojure.lang.LazySeq.sval(LazySeq.java:47)
        at clojure.lang.LazySeq.seq(LazySeq.java:56)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:560)
        at clojure.core$next.invoke(core.clj:61)
        at leiningen.deps$extract_native_deps.invoke(deps.clj:176)
        at leiningen.deps$deps.doInvoke(deps.clj:198)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.Var.invoke(Var.java:365)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.core$apply_task.invoke(core.clj:228)
        at leiningen.core$_main.doInvoke(core.clj:294)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.core$_main.invoke(core.clj:297)
        at user$eval42.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        ... 11 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:127)
        at java.util.jar.JarFile.<init>(JarFile.java:135)
        at java.util.jar.JarFile.<init>(JarFile.java:99)
        at sun.reflect.GeneratedConstructorAccessor6.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at clojure.lang.Reflector.invokeConstructor(Reflector.java:160)
        at leiningen.deps$extract_native_deps$fn__2277.invoke(deps.clj:176)
        at clojure.core$map$fn__3699.invoke(core.clj:2096)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        ... 31 more

What is the zip file that it can't find? Here is my project.clj:
(defproject checkin "1.0.0-SNAPSHOT"
  :description "universal checkin api"
  :dependencies [[org.clojure/clojure "1.2.1"]
                 [org.clojure/clojure-contrib "1.2.0"]
                 [fi.foyt/foursquare-api "1.0.0"]
                 [clj-yelp "0.1.0-SNAPSHOT"]
                 [compojure "0.6.4"]]
  :dev-dependencies [[appengine-magic "0.4.2"]]
  :repositories {"foursquare" "http://foursquare-api-java.googlecode.com/svn/repository"})

**Comment by gcv** [comment]
Your `project.clj` worked fine for me. I'm using Leiningen 1.6.1 on Mac OS 10.6. What version of Leiningen do you have installed, and on what platform?

**Comment by mvid** [comment]
$ lein version
Leiningen 1.6.1 on Java 1.6.0_26 Java HotSpot(TM) 64-Bit Server VM

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 11.04
Release:        11.04
Codename:       natty

Any ideas?

**Comment by mvid** [comment]
Looks like it was a corrupt jar in ~/.m2 

Sorry for the confusion
