### ISSUE TITLE
fails on Appengine Java SDK >= 1.6.4

### ISSUE THREAD

**Issue by delaaxe** [gcv/appengine-magic#59]
I followed all the instructions and when I
dev_appserver.sh war/
and point my browser to localhost:8080/ i get the following error: (also fails deployed on the appengine site)

HTTP ERROR 500

Problem accessing /. Reason:

```
Invalid method Code length 77527 in class file clojure/core__init
```

Caused by:

java.lang.ClassFormatError: Invalid method Code length 77527 in class file clojure/core__init
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:176)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at clojure.lang.RT.loadClassForName(RT.java:2024)
    at clojure.lang.RT.load(RT.java:417)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.lang.RT.doInit(RT.java:434)
    at clojure.lang.RT.<clinit>(RT.java:316)
    at clojure.lang.Namespace.<init>(Namespace.java:34)
    at clojure.lang.Namespace.findOrCreate(Namespace.java:176)
    at clojure.lang.Var.internPrivate(Var.java:149)
    at guestbookclj.app_servlet.<clinit>(Unknown Source)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
...

Fails sing Appengine Java SDK 1.6.4 or 1.6.5, works fine using version 1.6.3.1 though.
I have no idea how to fix this.

**Comment by gcv** [comment]
I have not yet updated appengine-magic for newer versions of the App Engine SDK.

The error you report is a little puzzling in any case. Do you have any AOT compiled .class files floating around in your project?

**Comment by delaaxe** [comment]
I can hardly provide more info. I did a lein clean and removed all .class'es but it didn't change a thing.

**Comment by sandaemc** [comment]
Didn't encounter that issue. SDK 1.6.5, Java 1.6. Just working out on hello world.

**Comment by tantaman** [comment]
I had this same problem as well.  I updated my project.clj to specifically depend on [org.clojure/clojure "1.4.0"] which fixed the issue.
