### ISSUE TITLE
Add Support for Lein 2

### ISSUE THREAD

**Issue by espeed** [gcv/appengine-magic#65]
``` bash
$ lein --version
Leiningen 2.0.0-preview7 on Java 1.7.0_06-icedtea OpenJDK 64-Bit Server VM

$ lein appengine-new
making a skeleton for a Google App Engine application
java.lang.NullPointerException
    at java.io.File.<init>(File.java:389)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at clojure.lang.Reflector.invokeConstructor(Reflector.java:180)
    at leiningen.appengine_new$appengine_new.invoke(appengine_new.clj:47)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$apply_task.invoke(main.clj:95)
    at leiningen.core.main$_main$fn__862.invoke(main.clj:156)
    at leiningen.core.main$_main.doInvoke(main.clj:155)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:601)
    at clojure.main$main_opt.invoke(main.clj:324)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at clojure.lang.Var.invoke(Var.java:423)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
```

**Comment by ghost** [comment]
I got similar problem about the leiningen version but kind of worse.
This is my step.
1. $lein new aeclj
2. $cd aeclj
3. $rm src/aeclj/core.clj
4. Edit project.clj: add [appengine-magic "0.5.0"] to :dev-dependencies
5. $lein deps
6. $lein appengine-new

Then I got this message print out in the terminal >>  'appengine-new' is not a task. See 'lein help'.
1. Try edit project.clj: add [appengine-magic "0.5.0"] to :plugins
2. again $lein appengine-new

Still not work but got a new message >>

making a skeleton for a Google App Engine application
nil

This is my leiningen version >> Leiningen 2.0.0-preview10 on Java 1.6.0_35 Java HotSpot(TM) 64-Bit Server VM

**Comment by gcv** [comment]
I really need update appengine-magic for the latest Clojure tool ecosystem. Sorry, I've just been incredibly busy — I'll try to find time in the next few weeks to take care of these problems.

**Comment by gcv** [comment]
There is experimental support for Leiningen 2 on the master branch. Patches welcome.
