### ISSUE TITLE
Error on lein appengine-prepare

### ISSUE THREAD

**Issue by canassa** [gcv/appengine-magic#67]
When I run `lein appengine-prepare` it output this error:

```
java.io.FileNotFoundException: Could not locate lancet/core__init.class or lancet/core.clj on classpath: 
    at clojure.lang.RT.load(RT.java:432)
    at clojure.lang.RT.load(RT.java:400)
    at clojure.core$load$fn__4890.invoke(core.clj:5415)
    at clojure.core$load.doInvoke(core.clj:5414)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5227)
    at clojure.core$load_lib.doInvoke(core.clj:5264)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$load_libs.doInvoke(core.clj:5298)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$require.doInvoke(core.clj:5381)
    at clojure.lang.RestFn.invoke(RestFn.java:482)
    at leiningen.appengine_prepare$eval13$loading__4784__auto____14.invoke(appengine_prepare.clj:1)
    at leiningen.appengine_prepare$eval13.invoke(appengine_prepare.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.load(Compiler.java:6952)
    at clojure.lang.RT.loadResourceScript(RT.java:359)
    at clojure.lang.RT.loadResourceScript(RT.java:350)
    at clojure.lang.RT.load(RT.java:429)
    at clojure.lang.RT.load(RT.java:400)
    at clojure.core$load$fn__4890.invoke(core.clj:5415)
    at clojure.core$load.doInvoke(core.clj:5414)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5227)
    at clojure.core$load_lib.doInvoke(core.clj:5264)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$load_libs.doInvoke(core.clj:5298)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$require.doInvoke(core.clj:5381)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at leiningen.core.utils$require_resolve.invoke(utils.clj:29)
    at leiningen.core.utils$require_resolve.invoke(utils.clj:31)
    at leiningen.core.main$resolve_task.invoke(main.clj:130)
    at leiningen.core.main$resolve_task.invoke(main.clj:135)
    at leiningen.core.main$apply_task.invoke(main.clj:159)
    at leiningen.core.main$_main$fn__1665.invoke(main.clj:237)
    at leiningen.core.main$_main.doInvoke(main.clj:221)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:601)
    at clojure.main$main_opt.invoke(main.clj:324)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at clojure.lang.Var.invoke(Var.java:423)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
```

I am using lein 2.0 and appengine-magic 0.5.1-SNAPSHOT

**Comment by intronic** [comment]
I had a similar problem. Does anyone have lein 2.0.0, appengine-magic 1.5.1-SNAPSHOT, and appengine SDK 1.7.4 working? (I fixed the above error, but still could not get lein appengine-prepare and lein appengine-update to work.)

**Comment by wiseman** [comment]
I'm having this issue as well.  Is appengine-magic a practical way to go for doing clojure on AppEngine, currently?  Are there alternatives?

**Comment by gcv** [comment]
Heroku?

Seriously, appengine-magic v0.5.0 does work. It does not support the latest Clojure, Leiningen, or the App Engine SDK, but it does work. Otherwise, patches welcome — Leiningen 2 support is the highest priority. I'll take care of it when I have time.

**Comment by cninja** [comment]
I got around this by adding [lancet "1.0.2"] to the :plugins section of the project.clj file.
